#!/bin/bash

# if you want to see more details uncomment the echo lines:

echo "begin: giddyup start hook" >> ${ROOT}/hook.log

export RAILS_ENV="production"
# echo "RAILS_ENV=${RAILS_ENV}" >> ${ROOT}/hook.log

source "/usr/local/rvm/scripts/rvm"

cd $RELEASE
# echo "cd $RELEASE" >> ${ROOT}/hook.log

# echo "ruby -v:" >> ${ROOT}/hook.log
ruby -v >> ${ROOT}/hook.log
# echo "rvm gemset name:" >> ${ROOT}/hook.log
rvm gemset name >> ${ROOT}/hook.log

# just in case we switch to using Passenger:
mkdir -p tmp/
touch tmp/restart.txt

mkdir -p shared/reports
ln -s "${ROOT}/shared/reports" "shared/reports"

bundle exec rake assets:precompile

sudo service osprotect start

echo "end: giddyup start hook" >> ${ROOT}/hook.log
echo "* * * all done (wait for a few seconds then go test it out) * * *"
