development:
  version: 1.0.0
  show_versions_and_limits: true
  pdf_max_records: 1000
  emails_from: do.not.reply@localhost

test:
  version: 1.0.0
  show_versions_and_limits: true
  pdf_max_records: 1000
  emails_from: do.not.reply@localhost

production:
  version: 1.0.0
  show_versions_and_limits: true
  pdf_max_records: 1000
  emails_from: do.not.reply@osprotect.appsudo.com
