development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: osprotect_dev
  username: rails
  password: rails
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_test
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock
