development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_dev
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_test
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect
  pool: 5
  username: railsapp
  password: r1o2r3dec20
  socket: /var/run/mysqld/mysqld.sock
