development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  # database: osprotect_dev
  # username: rails
  # password: rails
  # socket: /tmp/mysql.sock
  database: snort    
  username: railsapp
  password: cl0nesys01
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_test
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: snort    
  username: railsapp
  password: cl0nesys01
  socket: /var/run/mysqld/mysqld.sock
