# ... copy/backup a mysql db:
# > ssh ????_@_???.com
# > mysqldump -u railsapp -p osprotect > osprotect.sql
# > cd somewhere_local
# > scp ???_@_???.com:/apps/osprotect/current/osprotect.sql .
# > mysql -u rails -prails osprotect_dev < osprotect.sql

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_dev
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_test
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: osprotect_dev
  pool: 5
  username: rails
  password: rails
  socket: /tmp/mysql.sock
