process_event_notifications:
  # cron: "0 0 * * *"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1hr
  every: 1m
  class: CronTask
  queue: notifications
  # method to perform in app/workers/cron_task.rb:
  args: "event_notifications"
  description: "Notifications"
  rails_envs: development, production

email_notifications:
  every: 5m
  class: CronTask
  queue: notifications
  # method to perform in app/workers/cron_task.rb:
  args: "batched_email_notifications"
  description: "Email Event Notifications"
  rails_envs: development, production
